//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class xml_table
    {
        public int id { get; set; }
        public string FacilityID { get; set; }
        public string FacilityName { get; set; }
        public Nullable<double> WorkerID { get; set; }
        public string DateOfHire { get; set; }
        public string TerminationDate { get; set; }
        public string WorkDate { get; set; }
        public string JobTitleCode { get; set; }
        public string DepartmentCode { get; set; }
        public string PayCode { get; set; }
        public string PayType { get; set; }
        public string Hours { get; set; }
    }
}
